global:
  scrape_interval: 5s

rule_files:
  - "alert.rules.yml"   # Add this line to include alerting rules

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
